# Generated by Django 5.2.9 on 2026-01-01 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='アメニティ名')),
            ],
            options={
                'verbose_name': 'アメニティ',
                'verbose_name_plural': 'アメニティ',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=200, verbose_name='施設名')),
                ('capacity', models.IntegerField(default=0, verbose_name='最大宿泊人数')),
                ('description', models.TextField(blank=True, verbose_name='説明文')),
                ('short_description', models.CharField(blank=True, max_length=100, verbose_name='短い説明文')),
                ('address', models.CharField(max_length=200, verbose_name='住所')),
                ('num_parking', models.IntegerField(default=0, verbose_name='駐車場台数')),
                ('map_url', models.URLField(blank=True, verbose_name='Google Map URL')),
                ('management_entity', models.CharField(choices=[('IH', '自社管理'), ('CM', '委託管理')], default='IH', max_length=2)),
                ('amenities', models.ManyToManyField(blank=True, to='facilities.amenity', verbose_name='アメニティ')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='facilities/images/', verbose_name='画像')),
                ('caption', models.CharField(blank=True, max_length=50, verbose_name='キャプション')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='facilities.facility', verbose_name='施設')),
            ],
        ),
    ]
