# Generated by Django 5.2.9 on 2026-01-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_alter_facility_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='prop_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='プロパティキー'),
        ),
        migrations.AddField(
            model_name='facility',
            name='room_key',
            field=models.CharField(blank=True, max_length=50, verbose_name='ルームキー'),
        ),
    ]
